test/Android/ZumoE2ETestApp/libs/getLibs.ps1
test/Android/ZumoE2ETestApp/libs/getLibs.sh
test/Android/ZumoE2ETestApp/libs/required-libs.txt

Changes to add gcm libraries from outside grade

Changes to add gcm libraries from outside grade

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/MobileServiceSyncContext.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/ColumnDataInfo.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/MobileServiceLocalStore.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/SQLiteLocalStore.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/operations/LocalTableOperationProcessor.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/IncrementalPullStrategy.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationErrorList.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationQueue.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/framework/mocks/MobileServiceLocalStoreMock.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreQueryTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/OfflineTests.java

Fix issues:
SQLite error in table __errors in Android 2.0.1-beta #534
Android SDK thinks virtual fields from backend are missing columns #536
[Android] Android SDK throws an exception if the client and server table columns do not match #505

Fix Issues #534 #536 #505 

---

sdk/android/src/notifications-handler/build.gradle
sdk/android/src/notifications-handler/notifications-handler.iml
sdk/android/src/sdk/build.gradle
sdk/android/src/sdk/sdk.iml
sdk/android/test/sdk.testapp/build.gradle
sdk/android/test/sdk.testapp/sdk.testapp.iml
test/Android/ZumoE2ETestApp/ZumoE2ETestApp.iml
test/Android/ZumoE2ETestApp/build.gradle

Fix Issue #553 - Make sure all projects are updated to target API 21

Fix Issue #553

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/MobileServiceList.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceTable.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/ColumnDataType.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/SQLiteLocalStore.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationErrorList.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationQueue.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceFeaturesTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceTableTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreQueryTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/OfflineTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/UpdateDeleteTests.java

Support continuation tokens in queries (for paging) #417

Support continuation tokens in queries (for paging) #417

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/authentication/LoginManager.java

Fix Issue #577

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/ExecutableJsonQuery.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/ExecutableQuery.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/Query.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryBase.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryODataWriter.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QuerySQLWriter.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/MobileServiceSyncContext.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/IncrementalPullStrategy.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/PullCursor.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/PullStrategy.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceFeaturesTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/OfflineTests.java

Fix Issues #570, #571, #572, #573

Fix Issues #570, #571, #572, #573 

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/MobileServiceClient.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/authentication/LoginManager.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/LoginTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/LoginTests.java
test/Android/ZumoE2ETestApp/src/main/res/values/strings_activity_zumo_preference.xml

Fix Issues #350 - #414

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/MobileServiceClient.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/framework/filters/NullResponseContentFilter.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/framework/filters/NullResponseFilter.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/CustomApiClientTests.java

Fix Issue #559

---

sdk/android/android.iml
sdk/android/src/notifications-handler/notifications-handler.iml
sdk/android/src/sdk/sdk.iml
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/SQLiteLocalStore.java
sdk/android/test/sdk.testapp/sdk.testapp.iml
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreTests.java
test/Android/ZumoE2ETestApp/ZumoE2ETestApp.iml
test/Android/ZumoE2ETestApp/build.gradle

Fix pull action bug with SQLite

Fix pull action bug with SQLite

---

quickstart/iOS-Swift/ZUMOAPPNAME/ZUMOAPPNAME/Base.lproj/Main.storyboard

Fix crash with popover segue being caused as size classed were not enabled in the storyboard

QS: Swift: Enable size classes

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/MobileServiceConnection.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/MobileServiceJsonSyncTable.java

Fix Issue:
Update SDK with appropriate headers for data on calls against mobile services runtime #603

Fix Issue #603

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryNodeODataWriter.java

Fix Issue 613

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryNodeODataWriter.java

Reverts Azure/azure-mobile-services#617

Revert "Fix Issue 613"

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/MobileServiceConnection.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceClientTests.java

Fixing of Unit tests for issue #603

Fix UT Issue #603

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Push/Push.Test.cs

- Fix error introduced in the previous commit while rebasing.
- Also fixing a missing </param> tag warning.

Fix error introduced in the previous commit while rebasing.

---

sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
sdk/iOS/src/MSManagedObjectObserver.h
sdk/iOS/src/MSManagedObjectObserver.m
sdk/iOS/test/MSManagedObjectObserverTests.m

Unit tests to support PR #635 and associated with issue #568

Unit tests for new managed object observer

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.Net45/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.UI/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.WindowsPhone8/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.WindowsPhone81/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.WindowsStore/Properties/AssemblyInfo.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.Mobile.Net45.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Net45.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Test.Unit/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsPhone8.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsStore.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/MobileServiceClient.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.TestFramework/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/Properties/AssemblyInfo.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Properties/AssemblyInfo.cs

- Note that AssemblyVersion may be overridden by the build system (depending on how you build it)
- Fixed a UT to handle the change in version number.

Update AssemblyVersion to 2.* and fix UT

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/MobileServiceUrlBuilder.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/MobileAppUriValidator.cs

Remove use of #regions introduced in an earlier commit to be consistent with the rest of the codebase.

Remove use of #regions

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/DateTimeOffset.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryNodeODataWriter.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/ColumnDataType.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/SQLiteLocalStore.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/IncrementalPullStrategy.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceQueryTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreQueryTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/UpdateDeleteTests.java

Added support to DateTimeOffset on OData requests

Fix Issue #613

---

sdk/iOS/test/MSTableTests.m

Primarily trying out using TestExpectations for async testing within our unit tests.

iOS: Refactor insert table unit tests

---

sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java

Fix Incremental Pull Unit Test

Fix Incremental Pull Unit Test

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/ColumnDefinition.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/TableDefinition.cs

Subclassing the MobileServiceSQLiteStore to enable the use of encrypted
data SQLite providers (e.g. SQLCipher)

Increasing access to allow for inheritance.

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SystemPropertiesTests.java
test/Android/ZumoE2ETestApp/ZumoE2ETestApp.iml
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/OfflineTests.java

Fix System Properties error on implementation

Fix System Properties error on implementation

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/Query.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/query/QueryOperations.java

Saw some misnamed parameters in docs.  Fixed them.

Fixed comments.

---

sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
sdk/iOS/WindowsAzureMobileServices.xcodeproj/xcshareddata/xcschemes/WindowsAzureMobileServicesFramework.xcscheme
sdk/iOS/src/Info.plist

With Xcode 6, Apple has added iOS framework support for apps targeting iOS8 or later.

Support for dynamic iOS frameworks

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationErrorList.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java

Fix issue #718

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/pull/IncrementalPullStrategy.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java

#720 
-- Changed the incremental sync query logic to add parenthesis at appropriate location
-- Removed the redundant and clause in the incremental sync query
-- Fix the skip logic

Fixed the incremental pull query building logic and the skip reset bug #720

---

sdk/iOS/src/MSCoreDataStore.m
sdk/iOS/test/MSCoreDataStoreTests.m
sdk/iOS/test/MSSyncTableTests.m

This fixes https://github.com/Azure/azure-mobile-services/issues/699
In addition, this also fixes similar issue with readWithQuery.

[iOS][Offline] Fields with nil value are ignored on push operations

---

.gitignore
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationErrorList.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/OfflineTests.java

Added an E2E test to verify the fixed behavior

Added an E2E test to verify the fixed behavior

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceTableBase.java

Refactor on the method to avoid the parse of the response content if not needed.
Parse method wrapped with exception handling.

Fix Issue #751

---

sdk/iOS/src/MSClientConnection.m

[iOS] Fix memory leak when using NSURLSession

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/IMobileServiceTable.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.Generic.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Query/Linq/MobileServiceTableQuery.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncContext.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/IncrementalPullStrategy.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PullAction.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/FunctionalTests/Table/MobileServiceTableTest.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/MobileServiceTable.Generic.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/MobileServiceTable.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs

Breaking Change, removing use of query __systemProperties and leave all filtering or inclusion to use of $select

[Managed] Remove use of __systemProperties from the SDK

---

sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
sdk/iOS/src/MSClientConnection.m
sdk/iOS/test/MSClientConnectionTests.m

Sends Zumo-Api-Version header on all requests from the SDK to the server

[iOS] Send new Zumo-Api-Version header

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Http/MobileServiceHttpClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/IMobileServiceClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Push/PushHttpClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Query/OData/ODataExpressionParser.cs

I added a CancellationToken paramter to InvokeApi functions.
This modification was requested here: https://github.com/Azure/azure-mobile-services/issues/524

Add CancellationToken parameters

---

sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Http/MobileServiceHttpClient.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceSystemColumns.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceSystemProperties.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.Generic.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/CreatedAtAttribute.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/DeletedAttribute.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceContractResolver.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceSerializer.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/UpdatedAtAttribute.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/VersionAttribute.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceLocalSystemTables.cs
sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PurgeAction.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Query/MobileServiceTableQueryDescriptionTests.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Actions/PullActionTests.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Operations/InsertOperationTests.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Operations/MobileServiceTableOperationTests.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/FunctionalTests/Table/MobileServiceTableTest.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/SerializationTypes/SystemPropertyTypes.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/TestData/SystemPropertiesTestData.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/MobileServiceClient.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/MobileServiceObjectReaderTests.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/MobileServiceTable.Generic.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/MobileServiceTable.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Serialization/MobileServiceSerializer.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/Eventing/LocalStoreChangeTracker.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncContext.Test.cs
sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs

Changes to remove double underbar from System properties and add the Zumo api version header to http requests rebased onto each other.

[Managed] API Version Header & System Properties changes to Managed SDK

---

sdk/Javascript/src/MobileServiceClient.js
sdk/Javascript/src/MobileServiceLogin.js
sdk/Javascript/src/MobileServices.intellisense.js
sdk/Javascript/test/web/js/TestClientHelper.js
sdk/Javascript/test/winJS/default.html
sdk/Javascript/test/winJS/js/default.js
sdk/Javascript/test/winJS/tests/TestInterface.js
sdk/Javascript/test/winJS/tests/unit/mobileServiceTables.js
sdk/Javascript/test/winJS/tests/unit/mobileServicesClient._request.js
sdk/Javascript/test/winJS/tests/unit/mobileServicesClient.js
sdk/Javascript/test/winJS/tests/unit/push.js

Remove ApplicationKey,GatewayUri

[JavaScript]Remove ApplicationKey,GatewayUri

---

sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/MobileServiceClient.Test.cs

Fixing unit test for MobileApp branch

---

sdk/iOS/src/MSClient.m
sdk/iOS/src/MSLoginView.m

Fix cookie generated by EA (temp fix, long term we need to implement logout)
Fix case sensitive check on final login callback check

[iOS] EasyAuth bug fixes

---

sdk/android/build.gradle
sdk/android/src/sdk/build.gradle
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/AndroidHttpClientFactory.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/AndroidHttpClientFactoryImpl.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/ServiceFilterRequestImpl.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/ServiceFilterResponseImpl.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/framework/FroyoAndroidHttpClientFactory.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/framework/FroyoSupport.java

Fix Issue #776
Replace AndroidHttpClient with OkHttp (using the ApacheOkHttp implementation)

Fix Issue #776

---

sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/MobileServiceClient.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/authentication/LoginManager.java
sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/http/MobileServiceConnection.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/CustomApiClientTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/EnhancedPushTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/IdPropertyTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/LoginTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceClientTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceFeaturesTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceQueryTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceSyncTableTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/MobileServiceTableTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SerializationTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/ServiceFilterTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SystemPropertiesTests.java
sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/URLTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/MainActivity.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/EnhancedPushTests.java
test/Android/ZumoE2ETestApp/src/main/java/com/microsoft/windowsazure/mobileservices/zumoe2etestapp/tests/MiscTests.java

Changes on MobileServiceClient constructor to support easy auth

Changes on MobileServiceClient constructor to support easy auth
