- sdk/android/android-libraries.gradle
- sdk/android/build.gradle
- sdk/android/src/notifications-handler/build.gradle
- sdk/android/src/notifications-handler/notifications-handler.iml
- sdk/android/src/sdk/build.gradle
- sdk/android/src/sdk/sdk.iml
- test/Android/ZumoE2ETestApp/ZumoE2ETestApp.iml
sdk/android/android-libraries.gradle allows us to publish to jCenter (https://bintray.com/azuremobileservices/SDK/Mobile-Services-Android-SDK/2.0-beta/view) as long as you have a bintray account and is part of the azuremobileservices organization.
JAR files also codesigned.
> Codesigning Android JAR files & Publishing to jCenter

- sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
- sdk/iOS/src/MSCoreDataStore.h
- sdk/iOS/src/MSCoreDataStore.m
- sdk/iOS/test/CoreDataTestModel.xcdatamodeld/CoreDataTestModel.xcdatamodel/contents
- sdk/iOS/test/MSCoreDataStoreTests.m
- sdk/iOS/test/TodoItem.h
- sdk/iOS/test/TodoItem.m
Expose a helper function on MSCoreDataStore that makes it simple to go
from a NSManagedObject back to the expected dictionary format.
> [iOS] Helper function for NSManagedObject

- sdk/iOS/src/MSAPIRequest.h
- sdk/iOS/src/MSAPIRequest.m
- sdk/iOS/src/MSClientConnection.h
- sdk/iOS/src/MSClientConnection.m
- sdk/iOS/src/MSPushHttp.m
- sdk/iOS/src/MSTableConnection.m
- sdk/iOS/src/MSTableRequest.m
- sdk/iOS/src/MSURLBuilder.h
Moving all internal header usage to implementation files to hide from public scope.
I was testing with CocoaPods upcoming framework feature in their next release. Setting all internal headers to project scope using this I had errors with the internal headers used in the public headers not being available. I assume this is now closer to what is actually intended with internal headers.
> [iOS] Moving scope of internal headers

- sdk/iOS/src/MSCoreDataStore.m
- sdk/iOS/src/MSSyncContext.h
- sdk/iOS/src/MSSyncContext.m
- sdk/iOS/src/MSTableOperation.m
- sdk/iOS/test/MSCoreDataStoreTests.m
Fixing spelling error on property name. 
There was an open issue, but I can't find it presently.  No functional differences.
> Fix systemProperties name in SyncContext

- sdk/iOS/src/MSClient.h
- sdk/iOS/src/MSClient.m
- sdk/iOS/src/MSError.h
- sdk/iOS/src/MSLogin.m
- sdk/iOS/src/MSLoginController.m
- sdk/iOS/src/MSLoginView.m
The new gateway URL will be used only for authentication workflows.
> iOS: Add Gateway Support

- sdk/iOS/src/MSClient.m
- sdk/iOS/src/MSCoreDataStore.h
- sdk/iOS/src/MSManagedObjectObserver.h
- sdk/iOS/src/MSManagedObjectObserver.m
- sdk/iOS/src/MSSyncContext.h
- sdk/iOS/src/WindowsAzureMobileServices.h
Context observer for automatic message creation for entities saved with an NSManagedObjectContext. Also prevents the MSCoreDataStore from trying to re-insert/update/delete the entity and just creates the server message as discussed in issue #568
> [iOS] NSManagedObjectContext save observer

- sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Http/MobileServiceHttpClient.cs
- sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/MobileServiceClient.Test.cs
The MobileServiceClient constructor will rewire any delegating handlers passed in. This makes it difficult to do advanced handler stack scenarios.
> Fix scenario of single wired up delegating handler

- sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/localstore/SQLiteLocalStore.java
- sdk/android/test/sdk.testapp/src/main/java/com/microsoft/windowsazure/mobileservices/sdk/testapp/test/SQLiteStoreTests.java
This fixes issue #622. It does so by implementing a count of concurrent users of the database, and the last user closes the database. This way we maintain the behavior of allowing multiple threads to access the database at the same time, while preventing threads from closing the database out from under each other.
The unit test fails before this, and passes after.
> Fix for race condition in issue #622

- CHANGELOG.ios.md
- sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
- sdk/iOS/src/MSError.h
- sdk/iOS/src/MSQueuePushOperation.m
- sdk/iOS/src/MSTableOperationError.h
- sdk/iOS/src/MSTableOperationError.m
- sdk/iOS/src/MSUserAgentBuilder.m
- sdk/iOS/src/WindowsAzureMobileServices.h
- sdk/iOS/test/MSTableOperationErrorTests.m
- sdk/iOS/test/MSUserAgentBuilderTests.m
Previously these actions on the MSTableOperationError object would
essentially noop, now they will perform as documented
> iOS: Fix cancelAndUpdate/Discard Functions

- sdk/iOS/src/MSQueuePushOperation.h
- sdk/iOS/src/MSQueuePushOperation.m
- sdk/iOS/src/MSSyncContext.m
- sdk/iOS/src/MSSyncTable.m
- sdk/iOS/test/MSCoreDataStoreTests.m
- sdk/iOS/test/MSOfflinePassthroughHelper.h
- sdk/iOS/test/MSOfflinePassthroughHelper.m
- sdk/iOS/test/MSSyncTableTests.m
Fix completion blocks not occurring on the specified callback queue.
Surface operation write errors to callers when they occur post item update.
> iOS: Update synccontext errors and completions

- sdk/iOS/test/MSJSONSerializerTests.m
- sdk/iOS/test/MSPredicateTranslatorTests.m
- sdk/iOS/test/MSSyncTableTests.m
- sdk/iOS/test/WindowsAzureMobileServicesFunctionalTests.m
Modify some insert tests and fix up some unit test checks
Clean up some warnings from deprecations in iOS 8
> iOS: Update sync table insert tests

- sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
- sdk/iOS/src/MSClient.m
- sdk/iOS/src/MSCoreDataStore.m
- sdk/iOS/src/MSManagedObjectObserver.h
- sdk/iOS/src/MSManagedObjectObserver.m
- sdk/iOS/test/MSManagedObjectObserverTests.m
- sdk/iOS/test/MSSyncTableTests.m
Changing the observer usage pattern to take a context to observe directly.  Long term it should probably take an optional array to observe.
Updates test cases to reflect the change, and some minor other updates.
> iOS: Observe context directly

- sdk/iOS/src/MSCoreDataStore.m
- sdk/iOS/src/MSOperationQueue.m
- sdk/iOS/src/MSQueuePullOperation.m
- sdk/iOS/test/MSCoreDataStoreTests.m
- sdk/iOS/test/MSSyncTableTests.m
- Round tripping a GUID generated on iOS via the server (managed) results in the server pushing down a record with ID in a different case. Making ID comparisons case insensitive fixes bugs related to this.
> Make Id column operations case insensitive

- sdk/iOS/src/MSClient.h
Adding nullability annotations to MSClient relating to #669 . Only added to this class as a first stage and to receive feedback on these initial annotations and their usage.
I have run trials with this in my own Swift application and they seem be valid null/nonnull parameters. If these seem good and are accepted, can continue to markup other public classes in this trend.
> initial work on annotating nullable types for better Swift compatibility

- sdk/iOS/src/MSCoreDataStore.h
- sdk/iOS/src/MSCoreDataStore.m
- sdk/iOS/src/MSSyncContext.h
- sdk/iOS/src/MSSyncContext.m
Used for custom implementation of data insertion and requiring the sync context to only handle server message creation.
Won't cause any breaking changes to existing clients as the property for the MSCoreDataStore will default to YES. Does allow custom implementations per app for insertion into the data store, as experimented with in the multiple-contexts branch.
> [iOS] added property to turn off data store handling table operations

- sdk/iOS/src/MSClientConnection.m
- sdk/iOS/src/MSQueuePushOperation.m
- sdk/iOS/src/MSTableOperationError.h
- sdk/iOS/src/MSTableOperationError.m
- sdk/iOS/test/MSMultiRequestTestFilter.m
- sdk/iOS/test/MSSyncTableTests.m
- sdk/iOS/test/MSTableOperationErrorTests.m
Internal error check for a fatal network condition was incorrect, causing all operations to be attempted (and no early abort).  Fixed check, and improved tracked internal error so if non MS owned errors occur, the push operation correctly lets the dev know that.
> iOS: Fix handling of network errors on push

- sdk/iOS/src/MSSyncContext.m
- The write operation dispatch queue is defined as concurrent, however,
the tasks that run in it are not thread safe.
- Changing dispatch queue type from concurrent to serial will take care
of it
- In the future, if needed, we can change it back to concurrent and
make the tasks that run in it thread safe.
> [iOS] [offline] Fix potential race conditions while adding items to sync table

- sdk/iOS/WindowsAzureMobileServices.xcodeproj/project.pbxproj
- sdk/iOS/src/MSQueuePullOperationInternal.h
- sdk/iOS/src/MSSyncContext.h
- sdk/iOS/src/MSSyncContext.m
- sdk/iOS/src/MSSyncContextInternal.h
- sdk/iOS/src/MSSyncTable.h
- sdk/iOS/src/MSSyncTable.m
- sdk/iOS/test/MSSyncTableTests.m
Closes #703 by bringing these changes into dev branch first.
Returns NSOperation types from sync operations to allow the use to use them to react to changes. This could be to cancel, or to add these as dependencies to a trailing operation.
> [iOS] Returning operations from sync actions

- sdk/iOS/test/MSSyncTableTests.m
- Added UTs to test cancellability of push and pull operations at various execution points
- Removed UT testPullResultingInErrorAllowsDependentOperationsToComplete as completion of push/pull operation is covered by the newly added UTs
> Push/Pull cancellability UTs

- sdk/iOS/src/MSPredicateTranslator.m
- sdk/iOS/test/MSPredicateTranslatorTests.m
This will enable creating ODATA queries with guid objects in the query string.
Per: http://azure.github.io/guidelines.html#contributing
I work for Microsoft and I may not need to sign CLA. 
MS Alias: abhiku
> Add support for NSUUID in MSPredicateTranslator

- sdk/iOS/src/MSSyncContext.m
- sdk/iOS/test/MSSyncTableTests.m
Previously, a sync table’s insert check to see if an id was in use would not work as intended if the id was auto generated.  This should've only caused an issue if the table had a record with no id or if the GUID randomly generated did actually have a conflict.
> iOS: Fix incorrect error on insert with generated ids

- CHANGELOG.ios.md
- sdk/iOS/build.command
- sdk/iOS/src/MSCoreDataStore.h
- sdk/iOS/src/MSCoreDataStore.m
Updates the build command to include BitCode in the generated framework
Fixes an include issue in MSCoreDataStore that stopped it from being used via a cocoapod
> [iOS] Update build process to include BitCode, fix include issue

- .gitignore
- sdk/Javascript/Gruntfile.js
- sdk/Javascript/package.json
- sdk/Javascript/src/Microsoft.WindowsAzure.Mobile.JS.csproj
- sdk/Javascript/src/MobileServiceClient.js
- sdk/Javascript/src/MobileServiceSyncContext.js
- sdk/Javascript/src/MobileServiceSyncTable.js
- sdk/Javascript/src/Platforms/cordova/MobileServiceSQLiteStore.js
- sdk/Javascript/src/Utilities/Validate.js
- sdk/Javascript/test/cordova/.gitignore
- sdk/Javascript/test/cordova/config.xml
- sdk/Javascript/test/cordova/www/index.html
- sdk/Javascript/test/cordova/www/js/index.js
- sdk/Javascript/test/web/index.html
- sdk/Javascript/test/web/js/TestFrameworkAdapter.js
- sdk/Javascript/test/winJS/tests/unit/mobileServiceTables.js
- sdk/Javascript/test/winJS/tests/unit/mobileServicesClient._request.js
- Added a basic implementation of SQLite store based on litehelpers' SQLite
- Some TODOs are marked in code and needs to be taken care of.
- More UTs need to be added. This commit contains a single UT to test basic functionality.
- Tweaked the test framework adapter to start running the tests only when asked to do so. This makes it possible to trigger the tests when all required cordova plugins are loaded. WinRT implementation already does this
- QUnit adds new elements to the DOM which is not allowed in WinRT unless done in an 'unsafe' context. Implemented a hack to workaround this limitation without having to edit QUnit code. This implementation makes an implicit assumption on the QUnit code (that the only disallowed calls are the calls to the toolbar's appendChild() method)
- Ported …
> [Cordova] First set of changes for offline sync

- README.md
Turns out the links are case sensitive, so changed part of the hyperlink from "ios" to "iOS"
> Fix the broken links for iOS Reference Docs
